import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Container,Box,Heading,Text} from "@chakra-ui/react"
import  AdminHome from "../components/admin"
const Admin: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sakura Protocol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <AdminHome/>
      </>    
    </>
  )
}

export default Admin
