import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Container,Box,Heading,Text} from "@chakra-ui/react"

const Admin: NextPage = () => {
  return (
    <Container maxWidth="container.xl" bg="blackAlpha.300" h="100vh">
      <Head>
        <title>Sakura Protocol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Heading>Admin Page</Heading>     
    </Container>
  )
}

export default Admin
